swagger: "2.0"
info: 
    description: This is the swagger API that goes with our server code
    version: "1.0.0"
    title: REST API to call python funcs
consumes:
    - "application/json"
produces:
    - "application/json"

basePath: "/api"


# paths supported by the server application
paths:
    /emotions/{user_id}:
        get:
            operationRef: '../getTweets/emotions.get_sentiment'
            summary: "Return array of user sentiment analysis"
            parameters:
                - name: user_id 
                  in: path
                  type: string
                  description: Twitter User ID
                  required: true

                - name: timeScale
                  in: query
                  type: string
                  description: "Begin date for retrieving tweets"
                  required: false
            responses:
                200:
                  description: "successful"
                  schema:
                      type: string
